FROM python:3.11

WORKDIR /code

COPY ./requirements-dv.txt /code/requirements.txt

RUN pip install --no-cache-dir -r /code/requirements.txt

COPY ./data_viz /code/data_viz

WORKDIR /code

CMD ["streamlit", "run", "data_viz/app.py"]
