[tool.poetry]
name = "clg-env"
version = "0.1.0"
description = ""
authors = ["felipe_bizzo <fbizzo@magnasistemas.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
requests = "^2.32.3"
beautifulsoup4 = "^4.12.3"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
