FROM public.ecr.aws/docker/library/mongo:8.0.0-rc13-jammy

ENV CREATE_DB=true

WORKDIR /localfiles

COPY . /localfiles/

COPY ./initialize.sh /docker-entrypoint-initdb.d/

RUN chmod u+x /docker-entrypoint-initdb.d/initialize.sh

EXPOSE 27017